<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>SharedService.Core</PackageId>
    <Version>0.0.2</Version>
    <Authors>maxembo</Authors>
    <Company>maxembo</Company>
    <PackageDescription>Core</PackageDescription>
    <RepositoryUrl>https://github.com/maxembo/SharedService</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper"/>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Scrutor"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedService.SharedKernel\SharedService.SharedKernel.csproj" />
  </ItemGroup>

</Project>
